# Generated by Django 3.2.9 on 2021-11-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="webhook_url",
            field=models.URLField(default=None, max_length=512, null=True),
        ),
    ]
