# Generated by Django 3.2.9 on 2021-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0002_card_custom_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="custom_data",
            new_name="customer_data",
        ),
        migrations.AddField(
            model_name="card",
            name="user_id_for_organization",
            field=models.TextField(default=None, null=True),
        ),
    ]
