# Generated by Django 3.2.9 on 2021-11-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_webhook_url'),
        ('card', '0003_auto_20211114_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='provided_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_organization', to='organization.organization'),
        ),
    ]
