# Generated by Django 3.2.9 on 2021-11-13 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardOrganizationAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("user_id_for_organization", models.TextField(default=None, null=True)),
                ("customer_data", models.JSONField(default=None, null=True)),
                ("is_association_accepted_by_user", models.BooleanField(default=False)),
                (
                    "is_association_accepted_by_organization",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
