# Generated by Django 3.2.9 on 2021-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_usertype_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user_access_code',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='user_access_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
